// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCog34CaZqSaXR5OvXFZYrgoYTKX66gMqo',
    appId: '1:260214183612:web:02bf0b441d2dd7389422b9',
    messagingSenderId: '260214183612',
    projectId: 'be-and-to-be',
    authDomain: 'be-and-to-be.firebaseapp.com',
    storageBucket: 'be-and-to-be.firebasestorage.app',
    measurementId: 'G-2GX5H033S8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcKIEfqhCmXWZa7yLMfEacSii8KgcVm5M',
    appId: '1:260214183612:android:71891231178b917e9422b9',
    messagingSenderId: '260214183612',
    projectId: 'be-and-to-be',
    storageBucket: 'be-and-to-be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8ktfK82zVtLIScB5Ey_xagQI-4u6iOUQ',
    appId: '1:260214183612:ios:4ef4f434027076909422b9',
    messagingSenderId: '260214183612',
    projectId: 'be-and-to-be',
    storageBucket: 'be-and-to-be.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8ktfK82zVtLIScB5Ey_xagQI-4u6iOUQ',
    appId: '1:260214183612:ios:4ef4f434027076909422b9',
    messagingSenderId: '260214183612',
    projectId: 'be-and-to-be',
    storageBucket: 'be-and-to-be.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCog34CaZqSaXR5OvXFZYrgoYTKX66gMqo',
    appId: '1:260214183612:web:3682232af78741049422b9',
    messagingSenderId: '260214183612',
    projectId: 'be-and-to-be',
    authDomain: 'be-and-to-be.firebaseapp.com',
    storageBucket: 'be-and-to-be.firebasestorage.app',
    measurementId: 'G-12CHWS1ZC7',
  );
}
